# Site settings
title: Alex Vallejo 
general_email:
academic_email:

description: > # this means to ignore newlines until "baseurl:"
  Alex Vallejo. Software engineer.

baseurl: "" # the subpath of your site, e.g. /blog/

url: "https://valleyjo.github.io" # the base hostname & protocol for your site

# twitter_username: jekyllrb
github_username: valleyjo
linkedin_username: amvallejo
facebook_username:
# feel free to add other links here; you will have to add the SVG icon in _layouts/footer.html

# Build settings
markdown: kramdown

kramdown:
  math_engine: mathjax

# Other options
permalink: blog/:year/:month/:title